stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: none
  DOCKER_DRIVER: overlay2

build-develop:
  image: docker/compose
  stage: build
  services:
    - docker:dind
  tags:
    - develop
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.dev.yml build

  only:
    - develop

deploy-develop:
  image: docker/compose
  stage: deploy
  services:
    - docker:dind
  tags:
    - develop
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
    - docker-compose -f -f docker-compose.yml -f docker-compose.dev.yml exec -T php sh -c "composer install &&
                    php bin/console doctrine:migration:migrate  --no-interaction &&
                    php bin/console app:create:user:admin --no-interaction &&
                    yarn install &&
                    yarn encore dev"
  environment:
    name: develop
    url: http://beta-revivl.profsoft.online
  only:
    - develop


build-prod:
  variables:
    GIT_CLONE_PATH: /data/projects/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  image: docker/compose
  stage: build
  services:
    - docker:dind
  tags:
    - prod
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
  only:
    - master

deploy-prod:
  variables:
    GIT_CLONE_PATH: /data/projects/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  image: docker/compose
  stage: deploy
  services:
    - docker:dind
  tags:
    - prod
  script:
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
    - docker-compose -f -f docker-compose.yml -f docker-compose.prod.yml exec -T revivl-php sh -c "composer install &&
      php bin/console doctrine:migration:migrate  --no-interaction &&
      php bin/console app:create:user:admin --no-interaction &&
      yarn install &&
      yarn encore dev"
    - docker-compose -f  docker-compose.prod.yml logs
  environment:
    name: prod
  only:
    - master