version: '3.9'

services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: revivl_db
      POSTGRES_USER: postgres
    ports:
      - '5437:5432'

  nginx:
    ports:
      - '8780:80'