version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    volumes:
      - ./postgres:/var/lib/postgres
    networks:
      - revivl

  php-fpm:
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - MAILER_DSN
      - MAILER_SENDER
      - MAILER_HEADER
    build:
      context: .
      dockerfile: ./build/php-fpm/Dockerfile
    volumes:
      - ./revivl:/var/www/revivl
    depends_on:
      - postgres
    networks:
      - revivl

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./revivl:/var/www/revivl
      - ./build/nginx/develop:/etc/nginx/conf.d/
    depends_on:
      - php-fpm
      - postgres
    networks:
      - revivl

  mailhog:
    image: mailhog/mailhog:latest
    restart: on-failure
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - revivl

  cron:
    build:
      context: ./build/cron
    restart: always
    volumes:
      - ./revivl:/var/www/revivl:delegated
      - ./revivl/public:/var/www/revivl/public:rw,cached
    depends_on:
      - php-fpm
    networks:
      - revivl

networks:
  revivl: